apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-04T11:44:39Z
  labels:
    kops.k8s.io/cluster: chef.k8s.local
  name: nodes
spec:
  additionalUserData:
  - content: |
      INSERT-YOUR-USERDATA-HERE
    name: bootstrap.sh
    type: text/x-shellscript
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
